sudo: required
language: generic

services:
  - docker
before_install:
  - docker build -t rafiqueawan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rafiqueawan/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-980678568806"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

